name: Node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_for_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - name: Set up Node
        uses: 'actions/setup-node@v4'
        with:
          node-version: '23'

      - name: Build for linux
        run: bash ./scripts/build.sh

      - name: Upload linux executable
        uses: 'actions/upload-artifact@v4'
        with:
          name: my-language
          path: ./build/my-language

  build_for_windows:
    runs-on: windows-latest
    steps:
      - uses: 'actions/checkout@v4'

      - name: Set up Node
        uses: 'actions/setup-node@v4'
        with:
          node-version: '23'

      - name: Build for windows
        run: ./scripts/build.ps1 unsign

      - name: Upload windows executable
        uses: 'actions/upload-artifact@v3'
        with:
          name: my-language.exe
          path: ./build/my-language.exe